# yaml-language-server: $schema=https://github.com/connix-io/conclaude/releases/latest/download/conclaude-schema.json
# Conclaude YAML Configuration - Complete Default Configuration
# This configuration defines how conclaude handles Claude Code hook events
# All supported options are shown below with their default values

# Stop hook configuration - runs when Claude is about to stop
stop:
  # Structured command format with optional custom error messages
  # Each command can have its own error message, and control output display
  commands:
    - run: "spectr validate --all --strict"
      showStdout: true
      showStderr: true
      message: "Spec validation failed - please fix errors before continuing"
      maxOutputLines: 100

    - run: "nix develop -c 'tests'"
      showStdout: true
      showStderr: true
      message: "Linting failed - please fix errors before continuing"
      maxOutputLines: 100

  infinite: false

  # Message to send when infinite mode is enabled
  infiniteMessage: "continue working on the task"

  # Alternative to infinite mode - run for a specific number of rounds
  # When set, Claude will continue for the specified number of rounds
  rounds: null
  # Example: rounds: 3

# Pre-tool-use hook configuration - runs before tools are executed
# All file protection rules are consolidated in this section
preToolUse:
  # Prevent Claude from creating or modifying files at the repository root
  # Helps maintain clean project structure
  preventRootAdditions: true

  # Files that Claude cannot edit, using glob patterns
  # Supports various glob patterns for flexible file protection
  # By default, conclaude's own config files are protected to prevent the AI
  # from modifying guardrail settings - this is a security best practice
  uneditableFiles:
    - ".conclaude.yml" # Protect conclaude config from AI modification
    - ".conclaude.yaml" # Alternative config extension
  # Additional examples:
  # uneditableFiles:
  #   - "./package.json"      # specific file
  #   - "*.md"                # file extension
  #   - "src/**/*.ts"         # nested patterns
  #   - ".env*"               # environment files
  #   - "docs/**"             # entire directories
  #   - "{package,tsconfig}.json"  # multiple specific files

  # Prevent Claude from creating or modifying files that are git-ignored
  # When enabled, files matching patterns in .gitignore will be protected
  # Uses your existing .gitignore as the source of truth for file protection
  preventUpdateGitIgnored: false

  # Tool usage validation rules - control which tools can be used on which files
  # Allows fine-grained control over tool usage based on file patterns
  toolUsageValidation: []
  # Examples:
  # toolUsageValidation:
  #   - tool: "Write"
  #     pattern: "**/*.js"
  #     action: "allow"
  #     message: "Writing to JavaScript files is allowed"
  #   - tool: "*"
  #     pattern: ".env*"
  #     action: "block"
  #     message: "Environment files cannot be modified"

  # Directories where file additions are prevented (in addition to root)
  # List of directory paths where new files cannot be created
  preventAdditions: []
  # Examples:
  # preventAdditions:
  #   - "dist"
  #   - "build"
  #   - "node_modules"

  # Prevent editing of files with generation markers (enabled by default)
  # Checks for common markers like "DO NOT EDIT", "Code generated by", etc.
  preventGeneratedFileEdits: true

  # Custom message when blocking file edits with generation markers
  # Available placeholders: {file_path}, {marker}
  generatedFileMessage: null
  # Example:
  # generatedFileMessage: "Cannot modify {file_path} - it contains '{marker}' marker"

# System notifications configuration
notifications:
  # Enable system notifications for hook execution
  enabled: false

  # List of hook names that should trigger notifications
  # Use ["*"] to receive notifications for all hooks
  # Common hook names: "Stop", "PreToolUse", "PostToolUse", "SessionStart", "UserPromptSubmit", "Notification", "SubagentStop", "PreCompact"
  hooks: []
  # Examples:
  # hooks: ["*"]                    # All hooks
  # hooks: ["Stop", "PreToolUse"]   # Only specific hooks
  # hooks: ["Stop"]                 # Only stop hook notifications

  # Show error notifications (hook failures, system errors)
  showErrors: false

  # Show success notifications (hook completion, successful operations)
  showSuccess: false

  # Show system event notifications (session start/end, configuration loaded)
  showSystemEvents: true
